{% set version = "2019.6" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-statnet
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/statnet_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/statnet/statnet_{{ version }}.tar.gz
  sha256: 0903e1a81ed1b6289359cefd12da1424c92456d19e062c3f74197b69e536b29d

build:
  merge_build_host: True  # [win]
  number: 4
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ergm >=3.10.4
    - r-ergm.count >=3.3
    - r-network >=1.15
    - r-networkdynamic >=0.10.0
    - r-sna >=2.4
    - r-statnet.common >=4.2
    - r-tergm >=3.6.1
    - r-tsna >=0.3
  run:
    - r-base
    - r-ergm >=3.10.4
    - r-ergm.count >=3.3
    - r-network >=1.15
    - r-networkdynamic >=0.10.0
    - r-sna >=2.4
    - r-statnet.common >=4.2
    - r-tergm >=3.6.1
    - r-tsna >=0.3

test:
  commands:
    - $R -e "library('statnet')"           # [not win]
    - "\"%R%\" -e \"library('statnet')\""  # [win]

about:
  home: http://statnet.org
  license: GPL-3.0-only
  summary: Statnet is a collection of packages for statistical network analysis that are  designed
    to work together because they share common data representations and 'API'  design.  They
    provide an integrated set of tools for the representation,  visualization, analysis,
    and simulation of many different forms of network data.   This package is designed
    to make it easy to install and load the  key 'statnet' packages in a single step.  Learn
    more about 'statnet'  at <http://www.statnet.org>.  For an introduction to functions
    in this package,  type help(package='statnet').
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - stevierene82

# Package: statnet
# Version: 2018.10
# Date: 2018-10-17
# Title: Software Tools for the Statistical Analysis of Network Data
# Authors@R: c( person("Mark S.", "Handcock", role=c("aut"), email="handcock@stat.ucla.edu"), person("David R.", "Hunter", role=c("aut"), email="dhunter@stat.psu.edu"), person("Carter T.", "Butts", role=c("aut"), email="buttsc@uci.edu"), person("Steven M.", "Goodreau", role=c("aut"), email="goodreau@uw.edu"), person("Pavel N.", "Krivitsky", role=c("aut"), email="pavel@uow.edu.au", comment=c(ORCID="0000-0002-9101-3362")), person("Skye", "Bender-deMoll", role=c("aut"), email="skyebend@skyeome.net"), person("Martina", "Morris", role=c("aut","cre"), email="morrism@uw.edu") )
# Depends: R (>= 3.0), tergm (>= 3.5.2), ergm.count (>= 3.3), sna (>= 2.4), tsna (>= 0.2)
# Imports: ergm (>= 3.9.4), network (>= 1.13), networkDynamic (>= 0.9), statnet.common (>= 4.1.4)
# Suggests: ergm.rank (>= 1.1), ergm.ego (>= 0.4), EpiModel (>= 1.6.5), degreenet (>= 1.3.1), latentnet (>= 2.9.0), networksis (>= 2.1.3), relevent (>= 1.0.4), ndtv (>= 0.12.3)
# BugReports: https://github.com/statnet/statnet/issues
# Description: Statnet is a collection of packages for statistical network analysis that are  designed to work together because they share common data representations and 'API'  design.  They provide an integrated set of tools for the representation,  visualization, analysis, and simulation of many different forms of network data.   This package is designed to make it easy to install and load the  key 'statnet' packages in a single step.  Learn more about 'statnet'  at <http://www.statnet.org>.  For an introduction to functions in this package,  type help(package='statnet').
# License: GPL-3 + file LICENSE
# URL: http://statnet.org
# NeedsCompilation: no
# Packaged: 2018-10-22 07:32:48 UTC; morrism
# Author: Mark S. Handcock [aut], David R. Hunter [aut], Carter T. Butts [aut], Steven M. Goodreau [aut], Pavel N. Krivitsky [aut] (<https://orcid.org/0000-0002-9101-3362>), Skye Bender-deMoll [aut], Martina Morris [aut, cre]
# Maintainer: Martina Morris <morrism@uw.edu>
# Repository: CRAN
# Date/Publication: 2018-10-22 08:20:03 UTC
