appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: DTt7iHSryOVCo7yk4qA9jjNpdl3jaKIKcFb+lqhQPLPslWDuYavmPtKBL7PYamMTlGKlXDomoS9CW6m0EjW9OiHBO+uOrEcGNfSMjCNPo7uCvliuA7TtNW5jAkVkSoRMuXr/+ytyJTTfLMp/sDAXCAaPkpekW3fjoZFI6e0T3m1Mwc5XSq6x/t2zndz6Tj5GFhI4hBA390O0Z2IGV873ttrHEGXGmTzbFE7Er1U6cEPZT580sGL6HAkqsiC2efppPSQA503SQ4/tY0o6MK3Yn2zguz/orzFinkW+4CNXwDQmKSO4CZQcmszWDvyss+xIdncYhoS3VPYv6x7/mcimTfpVeJmaU8ia9hun9+K50OyR5KCo9115GwEJKQn3LLpOlZulVuN2QdonwyDGGVzNGILECf/ioLzl5sXr2Lua4CDADFs+M2+WO10VTorqxmu9Jj3HiJlzWDvzmC4vQObgnlPborEytalisJQZsPneKeRXg06w9ubra984WSjL3t58tn3S8DJ4BPfKct7RGtJ8df/Esw/+ioy/x/sBbBbJ0aQO82wMQZnYNntYa2788yo3uBzMjo/Fqvc63dLERQGtcM2C1KbQMH9shjiKTGWfH8HoEIEc1Cuvj92w/fVR1XX4FOfghtfMIoAwqsDeqlqEKcIjrNvmI/4peXgbVj9VTak=}
